site_name: Bosagora
nav:
  - Boascan Docs: index.md
  - Blocks::
      - Get latest blocks - GET /latest-blocks: getLatestBlocks.md
      - Get Block Height - GET /block_height: getBlockHeight.md
      - Get Block Height/:time- GET /block_height_at/:time: blockHeightat.md
      - Get Block Summary - GET /block-summary: blocksummary.md
      - Get Block Enrollments -  GET /block-enrollments: getBlockEnrollments.md
      - Get Block Transactions -  GET /block-transactions: getBlockTransactions.md
      
  - Validators::
      - Get Validators - GET /validators: getValidators.md 
      - Get Validators - GET /validators/:address: getValidatorAddress.md 

  - Wallet::
      - Get Wallet Transaction History - GET /wallet/transactions/history/:address: walletTransactionHistory.md 
      - Get Wallet Transaction Overview - GET /wallet/transaction/overview/:hash: walletTransactionOverview.md 
      - Get Wallet Block Header - GET /wallet/blocks/header: walletBlockHeader.md 
      - Get Wallet UTXO - GET /wallet/utxo/:address: walletUtxo.md 
      - Get Wallet Balance - GET /wallet/balance/:address: walletBalance.md 
      - Get Wallet Pending Transactions - GET wallet/transactions/pending/:address: walletPendingTransactions.md 

  - Holders::
      - Get BOA Holders - GET /holders : getHolders.md 
      - Get BOA Holder - GET /holder/:address: getHolder.md 
      - Get HolderBalanceHistory - GET /holder_balance_history/:address: holderBalanceHistory.md
      
  - Fee::
      - Get average fee chart - GET /average_fee_chart : averageFeeChart.md 

  - Search::
      - Get search  - GET /search/hash : search.md 

  - Coin Market::
      - Get coinMarketChart  - GET /coinarketchart : coinMarketChart.md 
      - Get Coin Market Cap for BOA. - GET /coinarketcap : coinMarketCap.md  
      - Get Boa Stats. - GET /boa-stats: boa-stats.md 

  - Transactions::
      - Get Latest transactions - GET /latest-transactions : latestTransactions.md
      - Get transaction - GET /transaction/:hash : getTransaction.md
      - Get transaction fee -GET /transaction/fees/:tx_size: getTransactionFee.md
      - Get transaction status - GET /transaction/status/:hash: getTransactionStatus.md
      - Get pending transactions - GET /transaction/pending/:hash: getPendingTransaction.md

  - UTXO::
      - Get utxo  - GET /utxo/:address : getUTXO.md 

theme:
  name: material
  custom_dir: docs/overrides/
  logo: 'https://i.imgur.com/H1Dfq7A.png'

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
